services:
  app:
    build: 
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    
    container_name: fastify_app
    command: [ "npm", "run", "dev" ]
    ports:
      - "9877:3000"
    env_file:
      - .env
    restart: always

  listener:
    build: 
      context: .
      dockerfile: ./docker/consumer/Dockerfile
    container_name: listener
    command: [ "npm", "run", "consumer-dev" ]
    restart: always
    ports:
      - "9878:3000"
    env_file:
      - .env
